### ISSUE TITLE
Good work

### ISSUE THREAD

**Issue by djsyl** [irekzielinski/Pylontech-Battery-Monitoring#2]
Hello,
Excelent work
That's exactly what I had and my head.
I will realize your project as it is and save a lot of time.
congratulations and thank you

**Comment by djsyl** [comment]
After a first try that did not work because of a bad max3232 ...
I change my max3232 in sparkfun and all is good yet bravo and thank you again for this contribution

**Comment by irekzielinski** [comment]
Great to hear that @djsyl !
