### ISSUE TITLE
Sofar Inverter

### ISSUE THREAD

**Issue by timecmdr** [irekzielinski/Pylontech-Battery-Monitoring#3]
Hi Irek,

I notice you have the same Inverter as me., Do you get the data about the power usage at your home from the battery data or do you use some other method to get it from the SOFAR?

**Comment by irekzielinski** [comment]
> I notice you have the same Inverter as me., Do you get the data about the power usage at your home from the battery data or do you use some other method to get it from the SOFAR?

Hi. Inverter has some kind of WiFi device (called iGen) and it has an API that I managed to communicate with, but can't decode the response. Older versions have been reverse engeneered (https://github.com/XtheOne/Inverter-Data-Logger) - but not this one. That was a reason for me to communicate with batteries directly.

To monitor house load/pv genertion I use "OWL Intuition-PV" device. It uses CT clamps and broadcases UDP packets on local lan with those details.
