### ISSUE TITLE
pwr output changed

### ISSUE THREAD

**Issue by alexandergeiler** [irekzielinski/Pylontech-Battery-Monitoring#30]
Hi,
I have a pylontech US2000B and a pylontech US3000A and I have been using @irekzielinski Pylontech-Battery-Monitoring tool since more than a year.
I am getting the data from pylontech and publish it to my moskitto MQTT broker and use it there.
Normally I switch off my battery at SOC < 20%, but last week my own program did not work and my US2000B battery went down to 0%.

Since then I have not been able to get any data from my US2000B battery.
The output has been changed:
US2000B:
![us2000](https://github.com/irekzielinski/Pylontech-Battery-Monitoring/assets/4689177/05199c62-cbc1-413b-b888-28a57213889e)
US3000A
![US3000](https://github.com/irekzielinski/Pylontech-Battery-Monitoring/assets/4689177/3f2837e9-1cb7-40df-94c7-53a9a1375648)

![info2000](https://github.com/irekzielinski/Pylontech-Battery-Monitoring/assets/4689177/03e4cba0-fcdc-417d-8ebf-7689b7755f2f)
![info3000](https://github.com/irekzielinski/Pylontech-Battery-Monitoring/assets/4689177/5a208f30-c1c2-4ea1-8788-576db202c47a)

Sure, I still get data from US3000A, but the irekzielinski program cannot read the data from US2000B.

Has anyone else seen this? Does anyone know how to change the output format?

**Comment by alexandergeiler** [comment]
I don´t know how, but my DIP configuration was wrong.
I changed all DIP switched to "OFF" and it is working again.
![US2000 changed](https://github.com/irekzielinski/Pylontech-Battery-Monitoring/assets/4689177/8c55538f-6971-4bd2-97da-3bcdf93bbefd)

**Comment by Rustimation** [comment]
I just discovered your issue after I fixed the problem differently.
Strangely though, I have all DIP switches set to OFF and still get the "other" response to the pwr command - which in turn renders JSON and MQTT output unusable. I have therefore changed Ireneus' software a bit to reflext the new parameter positions.
Please see closed issue #31 "New Pylontech Firmware - New Data Structure - New Problems".
Rgds
Chris
